name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Actions"

      - name: Set Hugging Face remote with token
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Hapus remote hf jika sudah ada, lalu tambahkan ulang dengan token
          git remote remove hf || true
          git remote add hf https://${HF_TOKEN}@huggingface.co/spaces/NaufalYP1/brat

      - name: Push to Hugging Face Space
        run: |
          # Push ke remote 'hf' (yang sudah berisi token) serta paksa update branch main
          git push hf main --force
