name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Configure Git user
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name  "GitHub Actions"

      - name: Push to Hugging Face Hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Buang remote origin lama (jika ada)
          git remote remove origin || true
          # Tambahkan ulang remote origin dengan token (tanpa username)
          git remote add origin https://$HF_TOKEN@huggingface.co/spaces/NaufalYP1/brat.git
          # Push ke branch main dengan force
          git push -f origin main
